sonar.projectKey=blastegit_Classe-plus
sonar.organization=classe-plus
sonar.projectName=Classe-plus
sonar.sources=.
sonar.language=py
sonar.python.version=3.11
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.db,**/instance/**
